export const ACTIONS = {
  CREATE_ROOM: "CREATE_ROOM",
  JOIN_ROOM: "JOIN_ROOM",
  START: "START",
  UPDATE_ROOM: "UPDATE_ROOM",
  SUBMIT_WORD: "SUBMIT_WORD",
  GIVE_UP: "GIVE_UP",
  RESTART: "RESTART",
  PING: "PING",
  PONG: "PONG"
};
